[package]
name = "StatCat"
version = "0.1.0"
edition = "2021"

[dependencies]
battery = "0.7.8"
chrono = "0.4.38"
dirs = "5.0.1"
nixinfo = "0.3.3"
serde = { version = "1.0.215", features = ["derive"] }
sysinfo = "0.32.1"
toml = "0.8.19"
