# This is the example config. Nerd fonts are required for the icons

[username]
text = "Username"
icon = "  "
color = "red"
[hostname]
text = "Hostname"
icon = "󰇅  "
color = "green"
[os]
text = "OS"
icon = "  "
color = "yellow"
[packages]
text = "Packages"
icon = "󰏖  "
color = "blue"
[terminal]
text = "Terminal"
icon = "  "
color = "magenta"
[shell]
text = "Shell"
icon = "  "
color = "cyan"
[desktop]
text = "Desktop"
icon = "󰍹  "
color = "blue"
[gpu]
text = "GPU"
icon = "  "
color = "red"
[cpu]
text = "CPU"
icon = "  "
color = "bright_green"
[memory]
text = "Memory"
icon = "  "
color = "bright_yellow"
display_mb = false
display_percent = false
[uptime]
text = "Uptime"
icon = "  "
color = "bright_blue"
# WIP. MAY NOT WORK.
#[battery]
#text = "Battery"
#color = "magenta"
#percentage = true
#charging_state = true
[colors]
text = "Colors"
color = "magenta"
icon = "  "
color_icon = "󰣏"
[time_date]
text = "Time/Date"
format = "%h %m"
color = "cyan"
icon = "󰺗  "
[general]
decoration = "nitch"
separator = ""
[order]
fields = ["username", "hostname", "os", "packages", "terminal",
"shell", "desktop", "gpu", "cpu", "memory", "uptime","colors"]

