# This is the example config. Nerd fonts are required for the icons

[username]
text = "Username"
icon = "  "
[hostname]
text = "Hostname"
icon = "󰇅  "
[os]
text = "OS"
icon = "  "
[packages]
text = "Packages"
icon = "󰏖  "
[terminal]
text = "Terminal"
icon = "  "
[shell]
text = "Shell"
icon = "  "
[desktop]
text = "Desktop"
icon = "󰍹  "
[gpu] # Significantly decreases speed, I need to rewrite
text = "GPU"
icon = "  "
[cpu]
text = "CPU"
icon = "  "
[memory]
text = "Memory"
icon = "  "
display_mb = false
display_percent = false
[uptime]
text = "Uptime"
icon = "  "
[colors]
text = "Colors"
icon = "  "
color_icon = "󰣏"
[time_date]
text = "Time/Date"
format = "%m/%d/%Y - %H:%M"
icon = "󰺗  "
[kernel]
text = "Kernel"
icon = "   "
[general]
decoration = "border"
separator = ""
# If you have border decoration and its "messy",
# you likely need to increase the padding number.
padding = 10
figlet = true
figlet_text = "StatCat!"
#figlet_arg = "-smushmode"
figlet_color = "magenta"
colors_order = [
"red", "yellow", "green",
"cyan", "blue", "magenta",
"red", "yellow", "green",
"cyan", "blue", "magenta"
]

# You can have 5 custom modules,
# custom1, custom2, up to 5
# To print it just add "custom1" to fields
# Replace 1 with whichever you want to print
[custom1]
text = ""
icon = ""
value = ""


[order]
fields = [
"username", "hostname", "os", "packages","desktop", "terminal",
"shell", "cpu", "memory", "uptime","time_date", "colors", 
]


