[config]


# Output of "statcat" command, words/letters contained in curly brackets are variables
# which can be user defined.
# See github for all pre defined variables.
output = [
  "╭───────────────╮",
  "│{RD}    Username  {WE}│  {username}",
  "│{YW}    Hostname  {WE}│  {hostname}",
  "│{GN}    Distro    {WE}│  {os}",
  "│{CN}    Packages  {WE}│  {packages}",
  "│{BE}  󱂬  Desktop   {WE}│  {desktop}",
  "│{MA}    Terminal  {WE}│  {terminal}",
  "│{RD}    Shell     {WE}│  {shell}",
  "│{YW}    CPU       {WE}│  {cpu}",
  "│{GN}    Memory    {WE}│  {used_mem_gb}GB/{total_mem_gb}GB",
  "│{CN}    Uptime    {WE}│  {uptime}",
  "│{BE}    Colors    {WE}│  {BK}{CI}{RD}{CI}{YW}{CI}{GN}{CI}{CN}{CI}{BE}{CI}{MA}{CI}",
  "╰───────────────╯",
]

[general]
figlet = true
figlet_text = "StatCat!"
# figlet_color cannot use variables, it must use either
# an ansi color code (which the default color variables are set to)
# or use a hex code.
figlet_color = "#F5C2E7"


# ASCII art must be under [general]
# You can use your colors and variables defined under [variables]
# If there is a backslash "\" there must be two or youll recieve an-
# error, ex: "\\"
# ASCII Art example:
#ascii = [
#"                     ",
#"                     ",
#"          /\\         ",
#"         /  \\        ",
#"        /\\   \\       ",
#"       /      \\      ",
#"      /   ,,   \\     ",
#"     /   |  |  -\\    ",
#"    /_-''    ''-_\\   ",
#"                     ",
#"                     ",
#"                     ",
#]


[variables]
BK        = "\u001b[30m" # Black
RD         = "\u001b[31m" # Red
GN       = "\u001b[32m" # Green
YW      = "\u001b[33m" # Yellow
BE        = "\u001b[34m" # Blue
MA     = "\u001b[35m" # Magenta
CN        = "\u001b[36m" # Cyan
WE       = "\u001b[37m" # White

CI = "󰣏 " # Colors icon

# border icons: ╭ ╮ ─ │ ╰ ╯




