[config]
output = [
  "username {username}",
  "hostname {hostname}",
  "distro {os}",
  "packages {packages}",
  "desktop {desktop}",
  "terminal {terminal}",
  "shell {shell}",
  "gpu {gpu}",
  "cpu {cpu}",
  "uptime {uptime}",
]

[general]

[colors]
blue = "\u001b[34m"
green = "\u001b[32m"
reset = "\u001b[0m"





